name: base_de_datos_universal
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  bitsdojo_window: ^0.1.6
  desktop_window: ^0.4.2
  flutter:
    sdk: flutter
  mysql1: ^0.20.0
  supabase_flutter: ^2.9.0
  window_size: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/