name: base_de_datos_universal
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  bitsdojo_window: ^0.1.6
  desktop_window: ^0.4.2
  file_picker: ^10.1.9
  dropdown_search: ^5.0.6
  flutter:
    sdk: flutter
  mysql1: ^0.20.0
  path: ^1.9.1
  supabase_flutter: ^2.9.0
  window_size: ^0.1.0
  intl: ^0.20.2
  auto_size_text: ^3.0.0
  pdf: ^3.11.3
  printing: ^5.14.2
  open_file: ^3.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/